# Basic
title: Kevin
subtitle: 
welcome_message: <a href="https://github.com/kevinfblog" target="_blank">Welcome</a>
description: Kevin blog.
creator: <a href="http://kevinfblog.github.io">@kevin</a>

url: "http://kevinfblog.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# emoji support
gems:
        -jemoji

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Kevin blog

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: kevin
    # duoshuo: 
    
# Social
social:
    github: kevinfblog
    mail: iamkevinf@gmail.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host

